%% ============================================================
%  QUADCOPTER 3-D ANIMATION
%
%  BLUE DASHED  = Reference / Desired trajectory
%  ORANGE SOLID = Actual trajectory
%
%  DRONE BODY   = Actual position + actual quaternion attitude
%
%  The attitude controller does NOT create a separate path.
%  It generates torque tau, which changes the actual attitude.
%  The actual trajectory is the result of the complete
%  closed-loop system.
%
% ============================================================

clc;

%% ============================================================
% 1. READ SIMULATION DATA
% ============================================================

t = out.xi_log.Time;

% Actual position
xi = squeeze(out.xi_log.Data);

% Desired/reference position
xi_r = squeeze(out.xi_r_log.Data);

% Actual quaternion
q = squeeze(out.q_log.Data);

% Number of samples
N = length(t);

%% ============================================================
% 2. FIX DATA ORIENTATION IF NECESSARY
% ============================================================

if size(xi,1) ~= 3
    xi = xi';
end

if size(xi_r,1) ~= 3
    xi_r = xi_r';
end

if size(q,1) ~= 4
    q = q';
end

%% ============================================================
% 3. DISPLAY INFORMATION
% ============================================================

fprintf('\n');
fprintf('============================================\n');
fprintf(' QUATERNION QUADCOPTER SIMULATION\n');
fprintf('============================================\n');

fprintf('Simulation duration : %.2f s\n', t(end));
fprintf('Number of samples   : %d\n', N);

fprintf('\nInitial position:\n');
fprintf('[ %.3f  %.3f  %.3f ] m\n', ...
    xi(1,1), xi(2,1), xi(3,1));

fprintf('\nFinal actual position:\n');
fprintf('[ %.3f  %.3f  %.3f ] m\n', ...
    xi(1,end), xi(2,end), xi(3,end));

fprintf('\nFinal desired position:\n');
fprintf('[ %.3f  %.3f  %.3f ] m\n', ...
    xi_r(1,end), xi_r(2,end), xi_r(3,end));

fprintf('============================================\n\n');


%% ============================================================
% 4. DRONE DIMENSIONS
% ============================================================

% Overall half arm length
L = 0.18;

% Central body dimensions
bodyLength = 0.20;
bodyWidth  = 0.14;
bodyHeight = 0.055;

% Arm thickness
armWidth  = 0.035;
armHeight = 0.025;

% Rotor radius
rotorRadius = 0.055;

% Rotor thickness
rotorHeight = 0.012;

% Number of points for circular rotors
nCircle = 24;


%% ============================================================
% 5. CREATE FIGURE
% ============================================================

fig = figure( ...
    'Name','Quaternion-Based Quadcopter Tracking', ...
    'NumberTitle','off', ...
    'Color','w');

hold on;
grid on;
axis equal;

xlabel('X (m)');
ylabel('Y (m)');
zlabel('Z (m)');

title('Quaternion-Based Quadcopter Tracking');

view(3);

%% ============================================================
% 6. AXIS LIMITS
% ============================================================

allX = [xi(1,:), xi_r(1,:)];
allY = [xi(2,:), xi_r(2,:)];
allZ = [xi(3,:), xi_r(3,:)];

margin = 0.30;

xlim([min(allX)-margin max(allX)+margin]);
ylim([min(allY)-margin max(allY)+margin]);
zlim([min(allZ)-margin max(allZ)+margin]);

%% ============================================================
% 7. REFERENCE TRAJECTORY
% ============================================================
%
% BLUE DASHED LINE
%
% This is xi_r(t), generated by RefTrajectory.
%
% It is the trajectory the controller is commanded to follow.
%
% ============================================================

hReference = plot3( ...
    xi_r(1,:), ...
    xi_r(2,:), ...
    xi_r(3,:), ...
    '--', ...
    'Color',[0 0.45 0.9], ...
    'LineWidth',2.0);

%% ============================================================
% 8. ACTUAL TRAJECTORY
% ============================================================
%
% ORANGE SOLID LINE
%
% This is xi(t), the actual position generated by the
% complete closed-loop system.
%
% ============================================================

hActualTrail = plot3( ...
    xi(1,1), ...
    xi(2,1), ...
    xi(3,1), ...
    '-', ...
    'Color',[0.9 0.35 0.05], ...
    'LineWidth',2.5);

%% ============================================================
% 9. START POINT
% ============================================================

plot3( ...
    xi_r(1,1), ...
    xi_r(2,1), ...
    xi_r(3,1), ...
    'o', ...
    'MarkerSize',8, ...
    'MarkerFaceColor',[0.2 0.7 0.2], ...
    'MarkerEdgeColor','k');

%% ============================================================
% 10. DESTINATION
% ============================================================

plot3( ...
    xi_r(1,end), ...
    xi_r(2,end), ...
    xi_r(3,end), ...
    'p', ...
    'MarkerSize',13, ...
    'MarkerFaceColor',[0.9 0.2 0.1], ...
    'MarkerEdgeColor','k');

%% ============================================================
% 11. LEGEND
% ============================================================

legend( ...
    [hReference hActualTrail], ...
    'Reference trajectory \xi_r(t)', ...
    'Actual trajectory \xi(t)', ...
    'Location','best');


%% ============================================================
% 12. CREATE LOCAL DRONE GEOMETRY
% ============================================================

% ------------------------------------------------------------
% Central body
% ------------------------------------------------------------

bodyV = createBox( ...
    bodyLength, ...
    bodyWidth, ...
    bodyHeight);

bodyF = boxFaces();

% ------------------------------------------------------------
% Four arms
% ------------------------------------------------------------

armX = createBox( ...
    2*L, ...
    armWidth, ...
    armHeight);

armY = createBox( ...
    armWidth, ...
    2*L, ...
    armHeight);

armF = boxFaces();

% ------------------------------------------------------------
% Rotor locations in BODY FRAME
% ------------------------------------------------------------

rotorPositions = [ ...
     L,  0, 0;
    -L,  0, 0;
     0,  L, 0;
     0, -L, 0]';


%% ============================================================
% 13. INITIAL QUATERNION
% ============================================================

quat = q(:,1);

quat = quat / norm(quat);

R = quatToRotmScalarFirst(quat);

p = xi(:,1);


%% ============================================================
% 14. CREATE BODY PATCH
% ============================================================

bodyWorld = transformVertices(bodyV,R,p);

hBody = patch( ...
    'Vertices',bodyWorld', ...
    'Faces',bodyF, ...
    'FaceColor',[0.25 0.25 0.28], ...
    'EdgeColor','k', ...
    'LineWidth',1.2);


%% ============================================================
% 15. CREATE X ARMS
% ============================================================

armXWorld = transformVertices(armX,R,p);

hArmX = patch( ...
    'Vertices',armXWorld', ...
    'Faces',armF, ...
    'FaceColor',[0.15 0.15 0.18], ...
    'EdgeColor','k', ...
    'LineWidth',1);


%% ============================================================
% 16. CREATE Y ARMS
% ============================================================

armYWorld = transformVertices(armY,R,p);

hArmY = patch( ...
    'Vertices',armYWorld', ...
    'Faces',armF, ...
    'FaceColor',[0.15 0.15 0.18], ...
    'EdgeColor','k', ...
    'LineWidth',1);


%% ============================================================
% 17. CREATE ROTOR DISCS
% ============================================================

theta = linspace(0,2*pi,nCircle);

rotorHandles = gobjects(4,1);

for i = 1:4

    localCenter = rotorPositions(:,i);

    % Rotor circle lies in local XY plane
    circleLocal = [ ...
        localCenter(1) + rotorRadius*cos(theta);
        localCenter(2) + rotorRadius*sin(theta);
        localCenter(3) + zeros(size(theta))];

    circleWorld = R * circleLocal + p;

    rotorHandles(i) = patch( ...
        circleWorld(1,:), ...
        circleWorld(2,:), ...
        circleWorld(3,:), ...
        [0.75 0.75 0.75], ...
        'EdgeColor','k', ...
        'LineWidth',1.0);
end


%% ============================================================
% 18. DRONE CENTER MARKER
% ============================================================

hCenter = plot3( ...
    p(1),p(2),p(3), ...
    'o', ...
    'MarkerSize',6, ...
    'MarkerFaceColor',[1 0.7 0], ...
    'MarkerEdgeColor','k');


%% ============================================================
% 19. ANIMATION LOOP
% ============================================================

for k = 1:N

    %% --------------------------------------------------------
    % Current position
    % ---------------------------------------------------------

    p = xi(:,k);

    %% --------------------------------------------------------
    % Current quaternion
    % ---------------------------------------------------------

    quat = q(:,k);

    % Normalize quaternion
    if norm(quat) > 1e-12
        quat = quat / norm(quat);
    end

    %% --------------------------------------------------------
    % Quaternion -> Rotation Matrix
    % ---------------------------------------------------------

    R = quatToRotmScalarFirst(quat);


    %% ========================================================
    % UPDATE ACTUAL TRAJECTORY
    % ========================================================

    set(hActualTrail, ...
        'XData',xi(1,1:k), ...
        'YData',xi(2,1:k), ...
        'ZData',xi(3,1:k));


    %% ========================================================
    % UPDATE SOLID BODY
    % ========================================================

    bodyWorld = transformVertices(bodyV,R,p);

    set(hBody, ...
        'Vertices',bodyWorld');


    %% ========================================================
    % UPDATE X ARM
    % ========================================================

    armXWorld = transformVertices(armX,R,p);

    set(hArmX, ...
        'Vertices',armXWorld');


    %% ========================================================
    % UPDATE Y ARM
    % ========================================================

    armYWorld = transformVertices(armY,R,p);

    set(hArmY, ...
        'Vertices',armYWorld');


    %% ========================================================
    % UPDATE ROTORS
    % ========================================================

    for i = 1:4

        localCenter = rotorPositions(:,i);

        circleLocal = [ ...
            localCenter(1) + rotorRadius*cos(theta);
            localCenter(2) + rotorRadius*sin(theta);
            localCenter(3) + zeros(size(theta))];

        circleWorld = R * circleLocal + p;

        set(rotorHandles(i), ...
            'XData',circleWorld(1,:), ...
            'YData',circleWorld(2,:), ...
            'ZData',circleWorld(3,:));
    end


    %% ========================================================
    % UPDATE CENTER
    % ========================================================

    set(hCenter, ...
        'XData',p(1), ...
        'YData',p(2), ...
        'ZData',p(3));


    %% ========================================================
    % UPDATE TITLE
    % ========================================================

    title(sprintf( ...
        'Quaternion-Based Quadcopter Tracking  |  t = %.2f s', ...
        t(k)));


    %% ========================================================
    % UPDATE GRAPHICS
    % ========================================================

    drawnow;


    %% ========================================================
    % ANIMATION SPEED
    % ========================================================

    pause(0.02);

end


%% ============================================================
% 20. FINAL MESSAGE
% ============================================================

fprintf('\n');
fprintf('============================================\n');
fprintf(' Animation completed successfully.\n');
fprintf(' Final simulation time = %.2f s\n',t(end));
fprintf('============================================\n');


%% ============================================================
% LOCAL FUNCTION: CREATE BOX
% ============================================================

function V = createBox(Lx,Ly,Lz)

x = Lx/2;
y = Ly/2;
z = Lz/2;

V = [ ...
    -x -y -z;
     x -y -z;
     x  y -z;
    -x  y -z;
    -x -y  z;
     x -y  z;
     x  y  z;
    -x  y  z]';

end


%% ============================================================
% LOCAL FUNCTION: BOX FACES
% ============================================================

function F = boxFaces()

F = [ ...
    1 2 3 4;
    5 6 7 8;
    1 2 6 5;
    2 3 7 6;
    3 4 8 7;
    4 1 5 8];

end


%% ============================================================
% LOCAL FUNCTION: TRANSFORM VERTICES
% ============================================================

function Vworld = transformVertices(V,R,p)

Vworld = R*V + p;

end


%% ============================================================
% LOCAL FUNCTION: QUATERNION -> ROTATION MATRIX
%
% Scalar-first convention:
%
% q = [q0 q1 q2 q3]'
%
% ============================================================

function R = quatToRotmScalarFirst(q)

q = q / norm(q);

q0 = q(1);
q1 = q(2);
q2 = q(3);
q3 = q(4);

R = [ ...
    1-2*(q2^2+q3^2), ...
    2*(q1*q2-q0*q3), ...
    2*(q1*q3+q0*q2);

    2*(q1*q2+q0*q3), ...
    1-2*(q1^2+q3^2), ...
    2*(q2*q3-q0*q1);

    2*(q1*q3-q0*q2), ...
    2*(q2*q3+q0*q1), ...
    1-2*(q1^2+q2^2)];

end %[output:03547ae8]

%[appendix]{"version":"1.0"}
%---
%[metadata:view]
%   data: {"layout":"onright"}
%---
%[output:03547ae8]
%   data: {"dataType":"image","outputData":{"dataUri":"data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAAcoAAAEVCAYAAABg9KUmAAAAAXNSR0IArs4c6QAAIABJREFUeF7tfX+wV8WV54kgPuHhTxD5IQSFoSI8VjRIYsQYUpNa9YXKOMhkyGZhC8lqsdSuMyxkU+xzdfhDCNk4Q6i4eWEXag2JDMm4DLFMpsYsuFEIAdGHEAJIBAQxCPIAfeLEbJ2L\/eW+++6Pvn27+3bf+7lVr\/Tx+sfpzzm3P\/d0nz79sauuuuqPhAcIAAEgAASAABCIReBjIEpYBhAAAkAACACBZARAlLAOIAAEgAAQAAIpCIAoYR5AAAgAASAABECUftjAkiVL6I477ugm7JEjR2j+\/Pl04MABq4OYPn06zZ07N+hzxYoVtHbtWqv9hzubN28e3XnnnVZwEOPu06dPIMKmTZto4cKFSmMvC8NJkyZRW1sbrV69OtBbWXIogSZRyZY9jBw5kpYtW0ZDhgyhNWvW0PLlyxvShf\/G\/3ju3Dmp94R1s3jxYmpubg7aOnPmDC1atIi2bNlSuG0J6FBEEQF4lIrA6awWnZzj2o6+qDr7j2vLlclVfDzY+mCIfqzETWSy2JeBYVyfZcghi1HecjbtYdWqVTRmzJhAxPD7FyVJMYYssoySpKgXtjHVtvPiiPL5EABR5sNLe+nwixF90cIvVpEJW0VoVyZXmxNjWBcvv\/wy3XDDDcGXv+2PFBV9iTqu6K3IGNLq2rCHOEIL2wB7tDNmzGh4kVu3bm14nnv27KFZs2bFDkHILt5lLiS8S7Fyodq2KbzR7nkEQJQlW0L0xYgucYZfWvEyJU0Wcf8e99LHvczhr2d+kdevX0\/Tpk0L0Akvvcp4XHF9hpcww39\/+umn6dZbbw2Wt\/gJe45hmYSaRDtZS19hwnjuuedoypQpxMupaRNZlGTuvvvuwKOI1gmX4+XNe+65pyF\/+IMmjrTEmLjNY8eONZbaRb0RI0YES95i6TdK0lH8wx9XwpbCJs14\/vznPw8m9qgu+fcoxlHPPSzvtm3bGu1w3SLL0iqvXZo9hNtL8tzCZZJkD6\/usE5YD\/wT1kMYE0GKAvuklY+wvYb7FvoUNqbSthhXFJ8sD1dFB3WtA6IsWfPCuNOWFqME+MADDwQTbLROtNw111zTbT8kPNTw5B83AYmy4ZctqVyYHOIma9GW6DNrIhPtPfjgg42lrzBR\/uQnP0kcl5jQkpaz07zDKH6tra0BMUS9+aylcqGXiRMn9tjnTcM6PDGL8Yb7jtvD5nJCR4MGDepGZOLDI44o03QQ7jNNXm7fprdtiyjnzJlD7e3tgQrER4ssUSat\/GQRpbCZhx9+uMfHmXin0laVZN7Nkqc6r7sHUZasvrgvyKhI0Rfl3nvvlSJKQahxpBidzPmrOc5bE5NweNIQ5aLe7hNPPNFYggqTeJg8ecL51a9+1SC6JJJN855lvroFSfG4ZPY34yayOG+ecQgTZbhtQWRRzMKenJA9\/AESJsDoEpwgI4EZj0d4+GE5oh8I4T7jPNuorLySER5v1MMJk2JcOVuvkY2lVzGWOHyTCC\/PylCYdMPLsRwsNHPmzGB1Iux1ZrWdx3Zt6alq\/YAoS9aoSaIMR8pGvRExwQsyTfKaxIQrvJW0r9qk\/bHwi8wT8He\/+90GUUY9kige0YmR5RGRiHGqiyN2Ga8nSfY4jz9uAg0TqMBMfFzEEWXch0SYPMNkFJU\/bQ9NJpgnvKcWXYKM7qMJrz5tSTa6J5e1YiDzyiXZGYgyPgI96lHaXhaX0anPZUCUJWsvz9KrmDxkPcqwVxUdZpQooxNhdMK95ZZbYr3YcLtpS0RhAixClGnLySyLKlEmLWuK8YVJLIlUo\/+eRpRhLz8OtziiTFsGzeNRvv7664kfKlFZBFFG92nTPvDKJkqZ\/mWIJOmDKG1Fo6yl16Ro2fBKQMlTndfdgyhLVl\/csop4QTdv3kzh\/bgsLzBMut\/+9rfpoYceCpZx4vacRFtZ+3CmPcrohJXHo0yb7PJEf8pMrIyD6K8MouT+RUBOVI5wsIkpjzIPUZp8pWQ8Shl96ibKLLmSlmyj9h5Hwlltx+Ed\/vCT2XowqbMqtA2iLFmLScdD4jwc4TXE7S9F9804GpNJmI83xO0p6tijTFtStbFHGRfokhZIk6Tq6B5q+GA51xGTVzQyNbykmnfpNa9HOWzYsMCjTwruyeNR8n5k3F5p2h6lT0Sp65VO8ihVj3CYOh6StJce7S+c1EAXRnVpB0TpgKazoihZxDDxZJWPRtDFDTHrGEbckmPS0l\/WEQXRlmzUa1yATLiNZ555ptsRivD40ggjSdVRIoxOKFEi5WMdcVmLTC69ij7FsZHoWJKifZlYf\/azn9EXv\/jFoIoIBMob9eoaUUZtysRrnESUMkkB4sjLZMKBtK0DGe\/ZBH5VahNE6ZA2s\/bJ4g49hycMcS5PEA3\/LRz4wpOdIJmoNxQmwbRzlNHjH3F7MlkHtqP7b7z\/KTKgRJeJopNSGtmG8ZFdepWJ4IyWScLQJFGylxvGXnycxJ31DNtRElEKu4l+\/MgSokwQmolXK8keTPSVRJTcV9Y53iQvL\/pu6ExhF3c0CySpxzJAlHpwNN4KT0xDhw7tkRfSeMcGOkiL6DTQHZoEAkAACBRCAERZCD5UVkEARKmCGuoAASBQFgIgyrKQr3G\/IMoaKx9DBwIeIgCi9FBpEBkIAAEgAATsIQCitIc1egICQAAIAAEPEQBReqg0iAwEgAAQAAL2EABR2sMaPQEBrxC45JJLiFMGcp7fXr160dmzZ2nnzp1ejQHCAgEdCIAodaCINoBARRBgcrz88ssDguT\/vv\/++3Tq1Cl67733iO\/K5N\/37t0b\/BseIFAXBECUddE0xgkEUhAQ3uPw4cODUkyInMDi0KFDjVrhMkyU8C5hUnVBAERZF01jnEAggkCS9\/jWW2+leozsaY4ePTpoLUqmABkIVBEBEGUVtYoxAYEEBJgcm5qagqVV\/mHPsauri5gc+SfPc9111xF7oOxd8nIst4UHCFQRARBlFbWKMQGBGO9RBOYwWYqlVSbHIgQnvEtu8+DBg92WaqEEIFAVBECUVdEkxgEENC2tqgAJ71IFNdTxBQEQpS+agpxAQBIB9u74\/srx48fTO++8Q6dPn7ayl8j9trS0ELxLSUWhmDcIgCi9URUEBQLJCIiIVF4K5R++t\/KKK66grVu30uHDh61CJ7xLXtLt6OgotLRrVXB0BgQSEABRwjSAgKcIiKhVce5RnHnk4Br+\/3HjxgVHOMo488iycWQsy4a9S08NDGI3EABRwhiAgGcIhDPmJAXmMEGVSZQC0rB3iUQFnhkaxAVRwgaAgE8I5D3z6ApRMsbwLn2yNMgahwA8StgFEHAYASYZPqvIRzv44SVVXsrMOvPoElHCu3TYwCCaFAIgSimYUAgI2EMgGpgjzjx2dnZK7ze6SJTCuxw7dmyQN\/aVV16h\/fv32wMWPQEBRQRAlIrAoRoQ0IlAWmBOlvcYJ4erRMmysmxTpkwJbiM5ceIEkqzrNCS0ZQQBEKURWNEoEJBDQCYwR66l7qVcJ0oONOLgHnFLCSJjVbSMOrYQAFHaQhr9AIGPEMgbmKMCnA9EKY6uMFnyURJc4aWiadSxgQCI0gbK6AMIfBT9qRKYowKeT0TJ4wtHxvJSM3ubeICAKwiAKF3RBOSoJAI6AnNUgPGNKMUYhdzwLlW0jjqmEABRmkIW7dYWAd2BOSpA+kqUUe8SF0SraB91dCMAotSNKNqrLQLCe+TlVX7EsY5Dhw5Zx8RnooR3ad1c0GEGAiBKmAgQKICAjcAcFfGqQJTCu+RgH3FBNAcA4QECthEAUdpGHP1VAgHVjDm2Bl8Vogx7lxwZy8+xY8dwQbQtQ0I\/AQIgShgCEJBEwNSZR8nucxWrGlGKweOC6FxmgMKaEABRagISzVQTAVeXVrPQripR8rh5bOxd4oLoLCvA33UhAKLUhSTaqRQCLgXmqABbZaKEd6liEahTBAEQZRH0ULdSCPjqPcYpoQ5EyeNmnbW0tMC7rNSb6N5gQJTu6QQSWUaASYUjK8VVVnx2j7PDqCQjtyx6Ynd1Icqod8lHcjo6OoKjOXiAgC4EQJS6kEQ7XiHgU2COCrB1I0rhXfLeJY8dSdZVrAZ1khAAUcI2aoNAlZZWs5RWR6KM8y45ZyyvEOABAkUQAFEWQQ91vUDA98AcFZDrTJTwLlUsBnXSEABRwj4qiUCdvMc4BdadKOFdVvK1Lm1QIMrSoEfHuhFgcmxqamoE5nBAR1dXl\/eBOSo4gSgvoBa+wgt7lyrWhDogStiA9whUPTBHRUEgyp6oiaw+uMJLxaLqXQdEWW\/9ezv6ui+tZikORBmPENvN2LFjacSIEfTKK6\/Q\/v37s6DE34EAcr3CBvxCoI6BOSoaAlEmo8bYTJ48mc6dO0cnTpwgRMaqWFi96sCjrJe+vRytIEee4PhH3PPY2dmJ0P8EjYIo04ly3LhxAUFykgnGipNL8O94gEAcAiBK2IWTCIilVZE1h8mRz8OJrDlOCu2QUCDKbKLkuy3ZngRW2Lt0yIAdEwVE6ZhC6i4OAnP0WACIUp4ouWQ4MpbJExdE67HDqrQCoqyKJj0eB09SAwcOpDFjxtCHH35Ip0+fbniOyKqiplgQZT6iFKXhXarZW9VrgSirrmGHx8cEOXz48GCfqF+\/fjRs2DDauHEjIhE16AxEqUaUwrtkm2TbhHepwRgr0ASIsgJK9GkISYE5PAaemMS+kU9jclFWEKU6UYa9S06yzs+xY8fo0KFDLqoaMllAAERpAeS6dyETmOPyxO6j\/lzGs2zZ8vYvEhWwd8mRsbjCy8c3opjMIMpi+KF2CgJ5AnPyTl4APh2BKJ7XXHod\/Yfxf0dtW\/6sdOjK1rVK\/1yHvUu2aaTBK92ErAsAorQOebU7VM2YozJ5VRvJYqML43nJucsCkhx39W1Bo0\/t\/SY9tXdZ8P\/9hg2nfsOuo+brzv83WGZ88Zf01uZfJgowrH8v+vTgPnT49B\/oxaPncgtatq6L9A\/vMre6K1EBRFkJNZY\/iHBgDkvDy1P85c0HuWWeIpOXTPt1KxPG8+b+\/5rmjf+7bhDsfPsFWtvvKbrhbxbQm798nn739Dp679ibdOmga+njX5pG135mMr341\/O6ESYT5F\/d3I\/u+5NLg7aYJKdvOJkb2rJ1XbR\/tvWWlhZ4l7k1728FEKUDups+fTrNnDmTHn30UdqyZUuiRPPmzaMZM2Z0+\/uZM2do0aJFqfVMDVFnxpyik5epMfrarsDz2P5TtPTmf+4xjF2tF9E\/9\/+\/tPHf\/SV9+C\/\/0uPvF\/XuTZ\/9Xz+k3i88S5\/\/3S\/oxr7v0YSrPuxR7tM\/Oh54lnmesnWtq\/9wkvWOjg7sXeYxAs\/KgihLVhiT5Ny5c4O8k1mEt2TJEho1ahTNnz+fDhw4UIrkMoE5KoLpmrxU+q5iHYHnH49cRvM\/sarbEH\/\/Jx+jH92ykX7x1fsyh\/65\/\/339N9eX03Xv741tuzf\/\/Y9+quNnZnthAuUrWud\/eMKr1yq97YwiLJE1THx3XHHHUFi5j59+mQS5apV5ye8WbNmWZfadDJynZOXdXAc7DC6R\/m5YX9BfzH6PweSbnzoIlp+1+BYTzI6FPYsH9y2jb7+nS8kjvK69mO5EChb1yb6xxVeuUzAu8IgypJUNmnSJGpra6PVq1fToEGDaOrUqalEOXLkSFq2bBnt27ePFi5caEVq1cAcFeFMTF4qclSlThyeY6+6jb5833LacMP\/oy0L\/mMw1OFD+9JnJg6k64b2paUrdtMlg\/vQJYMvps7tZxtQTFr6t7T03D918yp\/\/0Fv2nX2Ulp\/8I+0dku+q6rK1rWp\/uFdVuXt6TkOEKUDuuW9xyyiFMTKnmdzc3Mgtan9yaKBOSqQmpq8VGSpQp0kPFseWkBvbXmRLnl9G335SyNo4dxPXCDEf\/scXTz7Krrs5mY63H6M3vj+eU9x0G2T6X\/MuJFuefnpYD\/yv28\/S7zkqhoBWrauTfcP77IKb1D3MYAoHdCpDFGKvczNmzc3PEpeur355pszl2xlhpjnzKNMe3nLmJ688srje\/konkGk5o2D6e6v3UWTrnqNPtXSr9sQ\/2F\/C204+DYd\/eSmxr+\/f\/QcvfboIaJTQ+gzX5lG77R\/q8dxEJXzhWXr2kb\/8C59f4NAlM5pUIYo44RmL3Px4sW0fft2peVYm0urWaDbmLyyZKjS3xlP\/og6fPgwfXJ8f\/qzuwbR5287f6wj7vnqP32Ftp\/uSyP+tOey\/jvPXkJ93vkcdXx7aWL9PN5l2bq22T+8y2q8VfAoHdCjKlGq7luaDsxRgdTm5KUin091WL83\/6sR9NCDk+jmT3TRlZelH9\/41bHhxETZf\/gv6ZoJ\/zN2qMK7DO9dRgvKni8sW9e2+4d36dPbEy8riNIBHcoQZVwZ4VGuX7+eli9f3hjJ7NmzA2+Cj52IxyXvMQ5y25OXA2rXKkL0TOv3HxtA11zdS6qPr7\/QSv\/wWgv1eee\/0HUz0xNEhPcukxrPOl9Ytq7L6p9vJOE0eLggWsosnSoEonRAHTJEGbfMysdF+vfv3+NcJZPkihUr6OjRo\/TNb36Tjh8\/HlxlxQ8nduZsObIZc2zBU9bkZWt8JvpJO9Pa9p+uo7\/80ojUbg++8S4te\/Id+tnQ5fSHU0fp5IqpQdTr9W3DgoCepEfWu2RSYL1Gc6OWresy+xfeJd+\/ymenf\/3rXyNRgYmXQ3ObIErNgKo0F0eUHLwzZ84cam9vp7Vr1wbNCrIUUa9HjhxJTD4wePDgIMjn4x\/\/OD3++OP0m9\/8JiBHV28+KHPyUtFZmXVkAq\/GfWIwbfzxp3uIyeT4w6dfp329xtDJiV9pZObpO3kOvft8e6P8sK8NpqGzB8YOU4YoRcW4PbqydV12\/4wN373a2tpKu3fvph07dgQfsHjcRQBE6a5uCksmPEteguWAH5cfFyYvl\/HJu3TOeP6fVZOpZUwfYnI89MZZ+uHTBwOSFM81n\/oMffpbyxNzvf72qb8l+sTzPbzL3\/\/05PloWMknukfX2dlJ48aNK+3uURdsTQRbdXV1BQFXuOtS0phKKgaiLAl4G92CKG2gbLYP1TOtPBF\/+c9vpssvfZN+9PTrAVkmPXyDyPX3fTn489nDh+jMoYPdkqEPvX8QDZszKPg7e5M7vvQbpUEL77J3795BQnHOa1yGJ+UKUZb5saCkwBpXAlFWWPkgSj+VqyPZvG4yEHuXb7Qf65a1Jy\/CPLabbrqJJkyYQJs2baJdu3blbaJwed3YqAjkggwqcte1DoiywpoHUfqjXN3J5l2eiFm2KVOm0NmzZ4M8x3v37rXqWbqAjQsy+PN2lC8piLJ8HRiTAERpDFptDcsE5qh05vJELGRjguRo7LjIWJUxy9ZxARsXZJDFC+WIQJQVtgIQpZvKzRuYozIKlyfiqGy2zxe6gI0LMqjYVV3rgCgrrHkQpVvKVQ3MURlF1kR8+VeeoFM\/eECl6cJ14mQLR8byMSb2Nk09WdiY6jfcrgsy2BhnVfoAUVZFkzHjAFGWr1wdgTkqo0ibiC8efgtd\/m+eoK5XNtCZDY+oNF+oTpps4m8ms9e4QFIuyFBIiTWrDKKssMJBlOUoV3dgjsoo0ibi5taHqWl8K5168gH64OA2leYL1ckiibB3ycdHdu7cWai\/aOWs\/rV2ltCYCzLYGGdV+gBRVkWT8ChL16RLyeaTJuKLLh9MV81d30hZVwZosiRhyruU7d8kNi7IYHJ8VWsbRFk1jYbGA4\/SvHJtBOaojCJpIhbLru8+\/71uKetU+lCtk4ckwh8furzLPP2rjjGrngsyZMmIv19AAERZYWsAUZpTrs3AHJVRJE3EHMRz0RVD6Mw\/PlLKsiuPRYUkuA4nWefn2LFjhVK+qfSvooO0Oi7IoHtMVW4PRFlh7YIo9SrX1JlHvVKeby1uIhbLrh+8vq20iFdVohQY5bkgOglXF0jKBRlM2F1V2wRRVlWzRMGdlHzdFpKiqyvZ1aXVrBHFHsEY30r9Wx8uLYhHyFyUJIR3ybqJXuGVhUtRopZpX6ZMUQxk+kAZfQiAKPVh6VxLIEp1lbgUmKMyiriJWCy78r2TZT66SELVu9TVfxEMXZChiPx1qwuirLDGQZT5lOur9xg3yuhELJZdyzo7GZZRJ0mwzlpaWoLbSGS9S53957OwC6VdkEFV9jrWA1FWWOsgSjnl8qTFadT4hx+OruTsMPzj6xOdiPli5r6Tv1b6squppc\/wBdEdHR2pF5S7QFIuyOCrbZchN4iyDNQt9QmiTAbap8AcFXOJTsSuLLuaIkpuN3pBdNJlyC6QlAsyqNhVXeuAKCuseRBld+VWaWk1y2zDE\/G7l48KUtaVeXbS1NJrHA5h7zLuCi8XSMoFGbJsCH+\/gACIssLWAKI8r1zfA3NUTDQ6EQ\/4xlYnll1NepRhnNK8SxdIygUZVOyqrnVAlBXWfJ2Jsk7eY5wJuzwR25Qtzru02X\/S9OKCDBWe+rQPDUSpHVJ3GqwbUTI5NjU1NQJz+AaKrq4u7wNzVCzK5YnYtmxR77Kzs5PGjRsXJFvnwK0yHtsYlDHGKvUJoqySNiNjqQtRVj0wR8VEXZ6Iy5JNeJe9e\/cOluO3bNkColQxrhrWAVFWWOlVJsq6L61mmW1ZZJQll609yiQ52G5uuukmmjBhAm3atIl27dolI7L2Mi7rR\/tgK9AgiLICSkwaQhWJso6BOSom6vJEXLZs3P\/kyZPp3LlzdOLECYqLjFXBPE+dsjHIIyvKEoEoK2wFVSFKQY48ufAP7z3yDRK811TWHpPrZuPyRFy2bKJ\/JkhOMsG\/c3IJ\/t3WUzYGtsZZlX5AlFXRZMw4fCZKsbTKEwpPZkyOTIoia06F1aZlaOLeSRdS1kUHVDZJRPsXv7ON2fIuy8ZAi5HVqBEQZYWV7SNR8kTFJDlo0KDgv8J75C9+\/n88cgg0tz5MTeNbnTk7GZa6bJKI6z8cGavrgug0TZWNgZwVoZRAAERZYVvwhSh5kho2bBjddtttwZIq7xsJzxFLq\/kNVCRAv7jrBL27crpzy9Nlk0Ra\/7a8y7IxyG9V9a4Boqyw\/l0nSibI4cOHB0ur\/fr1C8hy48aNtH\/\/\/gprxfzQxLLr1b97lt786TIQZQTyLJIKB4yZ8i6zZDBvJeghDwIgyjxoeVbWRaJMCsxhaJk0yzwE7pl6E8XlBOh9B42k617+Du359SYQZU6iFMWZzEaPHh38yisdSUnWVewGRKmCWnl1QJTlYW+8Z1eIUiYwBxOHHnMQy65939kXEKWLHx5l6zpv\/6oXRGOPUo9Nu9AKiNIFLRiSoWyizJMxJ+\/kZQgy75u9ZHwr9W99mOgfF9CYy86BKGM0qmJrwrvMc0E0iNL716kxABBldXTZYyRlEKVqxhyVyavCqlMemrh38sMnv1p6PtOkQZSt6yL96\/Iui8igbByoqIwAiFIZOvcr2iTKcGAOI8NHOQ4ePBgc5JZ5MHHIoJReRiy78tnJXs8\/DqJMgKuorbGtt7S0BMeX2MZV9i6LylDcWtBCHgRAlHnQcqjsqlWrggCDhQsXJkplmih1ZszBxFHcuPpOnkN9J38tODvZ99Q+EKUhohTNhq\/w6ujoyHXOF\/Ze3N5ttgCizIH2vHnzaMaMGYk11qxZQ8uXL8\/RolpRJskxY8YESZ1tE6VMYI7KqDBxqKB2oY7wJv9w6iidXDE1SMtW9Cqp8B5zr1696OzZs8GeZ9FHh2xFZNDZf9oF0Wky6pShCBaoK4cAiDIDp0mTJtHixYupubmZ9uzZQ7NmzYqtMXLkSFq2bBkNGTKEzpw5Q4sWLQqu8dH5CFn69OkTJHTevn27NaI0nYwcE0cxSxFnJ999\/nv07vPtykSZtMf83nvv0YgRIwKvqWiat7J1baL\/uAuiQZTFbNql2iDKFG0wMS1YsICWLl2ai\/RU62UZxpIlS4LUbo888khAyvv27TNKlKqBOVnjiPu7iclLRQ6f6wz4xtZGyrq8eMp8COk6iJ9XNt06MdV\/Hu\/SlAy6sUJ75xEAUXpoCcJ7NUWURQNzVCDFxKGCWnIdGTxVP4SKHsSXkU0vGt1bM92\/jHdpWgaT+NWxbRClh1o3QZR5zjyagAwTh15Uk\/BkPTc1NQVpA8WtLF1dXUF0smyEspBU9ahE2bq20X+Wd2lDBr0WVe\/WQJQe6l8XUap6FCYgw8ShF9UonqY+hIR3meeoRNm6ttl\/kndpUwa9llXP1kCUHuq9KFHK7EfZhgUTh17EGU8+HnT48OHgvB\/\/Lu70ZM9R960sebzLsnVtu\/8479K2DHqtq36tgShz6DwcARtXzVS0a7SvLKKcPXt2MEmuXLmSVqxYQXPnzqVXX301mCzFje4mJ80ckDaKYuJQQS2+Dk\/M119\/PX32s5+l1157Lbi2THdS77ieZQ\/il63rsvrnd4+TrIs7VnEJgD6bN90SiFISYUFOXHz+\/Pl04MAByZr6i2URpUg0cPToURo8eDA99thjdPz48UAQcc9j3v0o\/aPo3mJZk5fpcdlqP5r8gY8QXXHFFbR169bAq7T5ZB3EL1vXZfYvvEs+RnbllVfSs88+q927t6nruvQFopTUtPAms84uSjZXqFgWUXLjTJB8lpNJ8\/HHH6cXXnghCNbgr1kXnzInLxfxkJGJz05e2XWosVIgVgn4Y4j\/v2jCARkZksqkBbOUreuy+2fM+O7V1tZW2r17N+3YsQNkWcTYLNQFUUqCLENOkk1ZK2Y6hZ3Ogbgweekcj8m2hPf4\/hf+hj4cNJau2fItOv3bX3b7EHIFz7hglrJlK7t\/tg2xh8wRx+zxq+SLNWljaLs7AiDKHBYxffp0mjNnDrW3t9PatWtz1CynKIiyHNxN9BqNUP6g6Sp6bVIbffD6Njr1gwd6dOkCGQihot5lZ2dnqd6uC9i4IIMJO61qmyDKHJp1JZhHVmQQpSxS7pbnvXC+AAAgAElEQVRLSv5w6tpbg3snT294hN5\/ZYPTRCmEE95l7969g0hcTvGoO\/pWRpMukJQLMshghTLnEQBRSlqCS8E8kiIH+5Mi6pX3Vl1+MHFc0I7MrSzi3klOgB73uIonj+2mm26iCRMmBEn9d+3aZd0sXcDGBRmsA+9xhyBKSeW5FMwjKTKIUhYoB8rluZVF3BSStOzKw3F5ImbZpkyZEtxGwkdXiiZZz6s+F7BxQYa8uNW5PIhSUvsI5pEESrFYXScOlYw54XsnPzi4zSuPMkziTJDiXK\/qBcgq5uaCrbkggwp2da0DosyheQ7m4cP769ats3LvZA7RYoti6bUogmbqF00dmLXs6oNHGT66Ej6Ib8O7dIGkXJDBjHVXs1UQpaReswJ5uBlbmXkkRcbSqyxQlsrpuJUleu9kkuguT8RxsoUjY\/m8LxOmqccFbFyQwRS+VWwXRFlFrX40JniU5StXJjAnj5TsTV484pbGvZNVIUoxDkEgOi6IdhkbEGUeqy+\/LIiyfB0YkwBEaQza1IbzBObkkVAmiCdKODt37izlCEbauLJIIuxd8vERHoPOJ6t\/nX25TNY2xlmVPkCUKZrk5dYFCxbQ0qVLgzNfso9qPdn2ZcuBKGWR0lPO9K0sl4xvTT07GR6FC2RQlCRMeZcuYOOCDHqsvh6tgCgz9Bzem9yzZw\/NmjUrtoaIiuVkx67sVYIozb\/ERQNz8kgoE8RTBY8yjEn440OXd+kCSbkgQx7bq3tZEGUOC5g3bx7NmDEjscaaNWucioYFUeZQbs6iOgJzcnZJA76xNTFlXbQtlydiFdm4Dl9RxU\/RK8NU+s+rq6zyLsiQJSP+fgEBEGWFrQFEqVe5Kmce9Uog35rLE3ER2fJcEF106Vce7fwli2CQvzfUKIoAiLIogg7XB1EWV47NpdXi0l5oweWJuKhswrtk3agkKijavw49uSCDjnHUpQ0QZYU1DaJUV67pwBx1yeRqsvysfz5m4VqeX10koepd6upfThPxpVyQoYj8dasLoqywxkGU+ZTrq\/eYtcRo8kxiPoTPl9ZJEqyzlpaW4DYSWe9SZ\/8q49eNgaoMqCePAIhSHivvSoIo5VTGEyenUeMffji6krPD8I\/vj4mo0aKYmCCq8AXRHR0dgSed9QFR5hlTExgU1QvqJyMAoqywdYAok5XrU2CODhPVGTVaVB5TJBG9IPrQoUOxoprqPw8uLsiQR966lwVRVtgCQJTdlevj0iqfnTz1gwe0Wanqvp42ATQvvcbJFfYu45Ksu0BSLsigU6dVbwtEmaJhTjbQ1tZGq1evprVr16bawpIlS4LgiUWLFuXK4mPSwECU59H1NTAnT8q6PHZUNGo0T19xZW2QRJp3aaP\/LIxckCFLRvz9AgIgygyiXLx4MTU3N1NaVh5uAkRZ7LXSPXH46D1GEZS5d7II6ra9S\/HBMmzYsEBsjsZN20ssMjZRN8671G1rKnK6IIOK3HWtA6KUIMpz587RVVddRfzfFStWxHqXIMpir5COiYMn4qampkZgDk\/CXV1d3gbm5ElZp4q+StRonr6SEsRzoBQHTdl4ot5lZ2cnhe\/DtCFDtA8d9l6G3HXtE0QpQZT85fvEE0\/QsmXLiHO5xnmXIMpir1CRiaOKgTni3smuVzbQmQ2PFANXonaeqFGJ5hrL3YMGDQr+nz9aiqaek+k3rYwYY+\/evQOZ+KIDW2QNoiyqvXLrgygliXLhwoVBSZHvNepdgiiLGXJeoqzC0moaYs2tD1PT+NbMeyeLod69tmzUaFKfPuiEZbzppptowoQJtGnTJtq1a5dOCKXbymvv0g2joBEEQJQ5iZKLh28KEd4liLKYfcpOHL4G5uRBRwTx\/OHUUTq5YmqeqlrKZkWNRjuJ0wkf\/nf1HCrb2uTJk4OtlBMnTlBcZKwWIFMakbV303KgfTkEQJQKRCmqhL3LI0eO0IABAxD1Kmd3PUqlTRxiIuYy\/COW8XivqaylM8VhSlUTy66nNzxC77+yQaqO7kJZ3qUP3mMSJsLWmCA5yQT\/zqTOv9t6QJS2kNbTD4iyAFFGvUtX7qEUQ\/L5eEhSEIjImqPH\/N1sxUYQj+zIo94lB0cNHz7c6yxGUZISv9tM9QeilLVAN8qBKDXpYfr06TRz5kx69NFHcY5SAdPwVz6TZDQIhL\/4TR8lUBBbexVTZyeLCMq6mThxIg0ePDi4lJwz3nBgjq86iSOpsAet64LoNMxBlEUs0n5dEKV9zK316ItHyZMUn6277bbbggmY942E51jFpdU0AzB9dlLW+OKO2vC\/XXnllfTmm2+Wsq8nK3tWuTSSsuVdgiiztOTW30GUbulDqzSuEyVPvGIZr1+\/fgFZbty4kfbv368VB58aK3vZNeuoTdbepQ9YZ5FUODjJlHeZJYMPONZJRhBlhbXtIlEmBeawGpg0y7zRoWxTsH12UoxXJTCHg2BGjx4dLIeXETVaRFeyJMXleIz86D4DKitDkXGirj4EQJT6sHSuJVeIUiYwBxOHffMpetQm7F3ajhotglZeWzOR6i+vDEXGi7rFEQBRFsfQ2RbKJsqsZbwwcJg47JiRiveYJZmtfb0sOWT\/rmJrwrtk\/GQviE6TR0UG2fGhnH4EQJT6MXWmxTKIUnUixsRh1mxMJwWwHTVaBK0itqbLuywiQ5Gxo64aAiBKNdy01BIJC0Rja9asoeXLlye2HS3PBdPObtokynBgDsvFe1d5srNg4tBiUt0aifto4b02k4kafPAui9oa49rS0hLki1X1LovKoN9a0GIaAiDKkuyDz13OnTuX1q1bF5Ajk+C0adMSbydhMTlN3qhRo2j+\/Pl04MCBTMlNE6XOjDmYODLVKV0g\/NFSxg0qNqJGpcGIKajL1ookktclQxEcUFceARClPFZaS65atSpob9asWY124\/4t3GnW36MCmiBKmcAcFaAwcaigdqFOnv3gYj3J1zYZNSovRc+SOm1N9biMThmKYIG6cgiAKOVw0lpKJFXft28fiVtJuAP2Ku+8885YjzGpTppgOomyaIRkFoCYOLIQ6vn3pI8Wm3c9ykita19Ppi+ZMiZsLW8ieRMyyIwdZdQQAFGq4Vao1qRJk2jx4sW0fv36bnuSTJRTp06NTazOddra2qhPnz7U3Nwc9J+VW7YoUaoG5qiAU9eJQ+XsZJL3yKnlXH10R40WGacpW8vjXZqSoQguqJuMAIiyBOtQIUqxp7l58+aGF5p1tZcqURYNzFGBtK4Th+y9kzY\/WlT0J1vHBe\/StK3JeJemZZDVB8rJIQCilMNJaykVoowTQLSzffv2bku4omweoix7j6uOE4fMvZOml7y1GrZkYzqiRiW7ii1mw9ayvEsbMhTBCHW7IwCiLMEiVPYo48TM2rfMIkqXvJQ6Thxi2fXd579H7z7f3lCxS3ox+XoUiRotIpdNW0vyLm3KUAQr1D2PAIiyJEvIG\/Uat3+Z5JlmeZQueil1nDiiCdDLWPIuyfy7fRRwPlXWv+qZRNkxCLvn5Pv88EqMjavb4rzLOtq7rJ5cLAeiLEkrec9Rxi2zMtn279+\/R5Ts7Nmzib3JlStXBucy+bzmq6++GkxG4kZ3niBcusqqbhOHWHa96NirdMnP\/2ugG\/5hvfh816Pq6ySzr6fStkveeTiRPOu47pcAqOizrDogyrKQ\/+g4yIwZMxoShDPzMJHOmTOH2tvbae3atUEZQZYi6vXIkSOxR0nEkuvRo0eDy3Yfe+wxOn78eNCGIEc+QuDSUzeivHzin9PFf\/p1uu7l71CvY68GehG6cUkvNmXJ2tfLI4uLqyYsvxjjkCFDgrs9n3322UDveNxGAETptn6UpWOCXLRoUeBZPv744\/TCCy84fSN9HYgyHDD11q1\/Tac\/1o+a1891Wi\/KBligoqp36ZL3mDV8Xv5tbW2l3bt3044dO0CWWYCV\/HcQZckKMNl9VjCPyb7ztl1VooybvE9TX3r7C9+irlc20JkNj+SFqhbl83iXPu7tsr3z+9nV1UWHDx8ml8\/A1sLgMgYJoqywFfhElDzZsby8R8dBFr4\/aUt\/smcnfcdAh\/xJ3qXA19e93ap+GOrQuYttgChd1IommXwiSh6ymDyYLPfu3evdcpTM0p\/M2UlN6q9MM8K7HDhwIL399tv03nvvBUFprgWk5QEcRJkHrfLLgijL14ExCXwjSgYi7IlxkMPOnTuN4aOr4TjvMemKsaSzk7pkqWI7At8xY8YEt+ecPXuWtm3bRrt27fJ2uCBKv1QHovRLX7mk9ZEoxQBFblD+nUPpXdvDifMeZe56FGcnTz357+nDU0dz6bNOhZO885MnT9K1114brD5w5DavPPj4gCj90hqI0i995ZLWZ6IUA3UhN2gY9GjgiKvHbXIZikOFZQNzfF+mB1E6ZHQSooAoJUDytUgViJKxF94lT6Kms7fE6dr3wBHX7TcJ387OztR96nBkrC\/L9OEVk3HjxgVbCzhH6bqFIoWd+xoqIGFViLIM71Is\/YlsRj4HjhQwIWNVk\/BVSbrgo3cJj9KYaRlpGB6lEVjdaLRqRMmo8gTb0tIS\/NeEdxlOCsD\/L1LKubZH6oaF5ZciCV\/ebyySd9W3IDAQZX7bKbMGiLJM9A33XUWijHqXPLl2dHQUnmRdzoNr2EyMNy9zbEaXEK4HgWHpVZem7bYDorSLt9XeqkyUwrsscvOEq\/lArRqJwc7KxNe1ILAozPAoDRqegaZBlAZAdaXJqhNlnHeZlajApncj5OOzkx8c3OaKWRiVQ\/XYjAmhyg4CSxsTiNKExs21CaI0h23pLdeFKGW8S9ljByaUVoezk2LpWmTM4RymvO\/owi01LnqXIEoTb5q5NkGU5rAtveU6EWWcd8nBPuHoShGYk3XsQKfiRMq6D17fRqd+8IDOpktvy1RgjomBmQ4CyysziDIvYuWWB1GWi7\/R3utIlAwoezW33nor8VVGfDPDnj17Srvr8ZLxrdS\/9WE69eQDlVh+LWPpWudLEk6yXjQIrIhcIMoi6NmvC6K0j7m1HutElHHezUUXXUT9+vWj06dPl5ZkXSy7nlwx1ZreTXRUZmCO7vGEExWYOGIkIy+IUgYld8qAKN3RhXZJqk6UMt5NmZOiWHb19d5JGXy1G63FBlUviNYhIohSB4r22gBR2sPaek+DBw+mFStW0NGjR2nu3LnW+zfVoUpSAF6O5aMkNq\/w6jt5DvWd\/DXvll3rlM\/W9oeUsF3eFuCH714tkmjB1DuGdrsjAKKsuEUIr5LJcvHixd5eiqzDuwlPiqZvnvDt3kmfAnNMvLImvcs42+3bty998pOfpNtvv51++tOf0sqVK00MC21qQgBEqQlIl5thz\/Luu++m+++\/PyBKn7zLuL2xpLseZXVgIzeoD\/dOJuVb5Y+IOibq1u1dRm33yiuvDALMOAUjf8Dyxyu\/j88884y3H7Cy75zv5UCUvmswh\/z8ci5atCio4fJXrI1D6+FJ0cTNExzEc\/GIW5xcdq1SYE4O85cuWsS7TPMe77vvvkAGJkiX3z9poGpUEERZI2WLoc6ePbvhXfJyLL+4Ljxl7I2Z8C5dPDupY+naBRuxJUMe75LLNjU1BceSRMIF4T3y8iq8R1taM9cPiNIctk63LLxLXpb9\/ve\/X9oeifBumLD4RyQFKHqbRB7wwx6WDu\/SpbOT0Y8Pxrfo0nUebH0vmxYEFt3XZXLs1asXTZw4kT7\/+c8HH6D8w0ur7EHi8RcBEKW\/utMieRnepat7Y7punij77GTSx4fNjERajNORRsLe5cmTJ+n48eOB5yg+7MKBOfzhKZZWmSBdWa1xBEpvxQBReqs6fYKLYySmvUtfIit15AZlr\/L9VzboU1JGS0kfHyoXIVsT2qOOGN8bbriB7rjjDjp37hy9++67dMUVVyAwxyMdFhEVRFkEvYrVFd6lOHep42vY170xl2+eCJudLx8fPr4qcZ4570XeddddNGXKlGBICMzxUbP5ZQZR5ses0jXYq+TIWN7DLLJ3WZXISh3epW6D8fXjQzcOJtqL88x5aZXPOw4dOrRbYM4999zTSOah46PSxHjQph4EQJR6cKxcK2HvUjZRQVUncB4Xn33j\/5aVG5QNzMSZ0soZruKA4gJz+Mwj\/4jAHD7z+NJLLzUCc8IflXw2mf+Op5oIgCirqVcto5L1LusSWVnGzRM2zpRqMRYPG0k788gepGxgDn9U8oPsOh4agaTIIEpJoOpcLM67rOsEnud8narNxJ3L46AcBOaoItq9XvTDjo91DBw4MEgphzOPejCuWisgyqpp1NB4wt7lk08+STt27AjOPNZ1Ai+SvSVJRQjMMWS8oWXr8HldvoaNs+Ww98gP7zOyV4gzj+b04GvLIEpfNWdRbv7K5lyxHLywa9cuuvHGG+nEiRNBkvUXX3zRoiRudaXDu6zqvq4LmpINzGFi5L1H7DG6oDU3ZQBRuqkXp6QSUbA8kYh9GB2RsU4NsoAwKt5lVaKCC8BmrKpKYI4xYdBwJRAAUVZCjWYHIYIaor2wh8mE6fsVXjrQk\/Eu4T3qQDq+DV2BOeYkRMs+IwCi9Fl7Dsge3rvkJSxejq3zE+ddRoNHRFAO57PFUwwB1wNzVq1aRWPGjAkGeeTIEZo\/fz4dOHCg2KBR2zoCIErrkFezw6pcEK1DOzx5jx07lkaMGNEIeCoj2buOsbjYRlzGHBcDc5gk+\/fv3yBH\/p2fWbNmuQgrZEpBAEQJ89CGQNi79O2CaB0gRJf\/Lr30Urr66quJPUfGo46XIevAldvwLTBn0qRJ1NbWRqtXr6a1a9cGMEyfPp1mzpxJjz76KG3ZskUXNGjHAgIgSgsgu9jFyJEjadmyZTRkyJBAvD179mj70q2bd5kWmBPeu2TC3Lt3r4vm4KxMUWzFPY8DBgwIorB5fzyaMcfVwTBRzpkzh9rb2xvk6aqskKs7AiDKGlqEIMnTp08H5Ch+37dvHy1cuFALIuxd8pGS+++\/P5jIOMVXlZ68gTkmLoiuEp7hsaQF5vC5R358S0YefeeqqruqjgtEWVXNpowrbglo3rx5dOedd2oPNhAXRLM4HOzje5qvIun6wt6ljguiq2a6rgfmqOItAnr4eq4VK1bAm1QFssR6IMoSwXepaybKqVOnBsc9TOyflHFBtC5844JHjh07RqoXIcO7vKCZuGxEHJjDtsjJyIX3WIWMOfyByisr69ato+XLl+syT7RjAQEQpQWQXe+CAw\/EDSG6ll7jxiy8S9MXROvAOy54RGe6vvDeW928yzqfeUTkq463034bIEr7mDvTYzig58yZM8a8yeiAXfYuk\/KtHjp0yIjexAXR3Dh7qab6MSJ8zkaTAnP4CrOqJSNPCtwBUeY0GkeKgygdUUTZYvDS67Rp06ztobBXyfs1LniXeQNzTOjKxQuidYyzioE5MriIj1AuK5IM2H7HZOREGTkEQJRyOFW+lInIVxnQwld48f6NzZvi44518MXMZWXMEd4ly1XmBdEyessqw2O55pprgh9++vbtG1yCXKerrKJHsBDMk2U17v4dROmuboxJFhe4UxZR8iBlL4jWAYjuwBwdMkXb8NW7jFu2Hjp0KE2cOLERmMNHhZ555hlcZWXCcNCmMQRAlMagdbdhEbzzxhtvNJIMLFmyJNgnMhX1KoNG3AXRMvWyyvAE3tTU1PBwfLhHk2XmvTvXvcs6B+Zk2R3+Xh0EQJTV0WWukQiybG5uDurZDOZJE1Snd5kUmMNLq0yWPjzhJOsdHR3OyF2nwBwf7AQymkUARGkWX7SuiICqd+lCYI7ikBOrhRMVlLl3WdfAHN36RHv+IQCi9E9ntZE4j3eZlm+1KoCpXBBddOxxy9Yi32qdAnOK4oj6fiMAovRbf7WQPsm7rKL3mKVQW95ldNmaybFXr16NwByOTuYfBOZkaQx\/rwICIMoqaLEGY4h6l5s2bWocPajjRcgmvEsE5tTgRcIQlRAAUSrBhko2ERA3kXBULv\/wc+LEiSBf5i9+8QtnAlxsYsJ96fIuEZhjW3PozzcEQJS+aayG8vLSa\/TuQf43Jk2+kYTz1Nb5UfEu486TcjLy22+\/nXy9yqrONoCxm0UARGkWX7SuAQH2KOMy9tTtgug0KGW8y7hE75wxh8mREwOIfKv88fHSSy8F94jiAQJAgAhECSvwGoHw3mUVL4jOqxxOGTd69OhgOXrv3r3E+7dxgTmcTo5\/+Cor\/ghh7JgcmSTxAAEg0B0BECUsohIIwLu8oEYmxrFjx9KQIUPoww8\/DMiSiZO9Rz7SwR6k8NKZGDly1WaO3UoYHAZRKwRAlLVSd7UHK4J+7r\/\/\/sBD4iTrdXuYJIcPHx5EBPfr14\/Gjx8feJRMmlW7yqpuusV4y0MARFke9pXqme\/ZGzNmTGNMa9asSb3FnROzz5gxoxsGutLoiZy13Dh7TCtXrqwU1tHBJAXmcFAOe4\/iYa\/x3nvvrTQWGBwQMIEAiNIEqjVrk0myf\/\/+jXv3+NJa9ubWrVuXSJachH3UqFGNOiYgc\/mC6KLjzRuYw\/3x\/Z9MlhwljECdohpA\/TohAKKsk7YNjFUkV1+\/fn03Usy6yT3r77pEFd6lCxdE6xhTkcAcEfjEJFl1L1sH1mgDCAgEQJSwBSMIpBFhGXdf+uxdImOOERNFo0BAGgEQpTRUKCiLgPAy2XNZuHBhj2r897a2NurTpw\/ZvOaLPSpefvTFuwwH5jCInG914MCBQeQqAnNkrRHlgEBxBECUxTFECyEEhLfI\/zR\/\/nw6cOBAD3zEHubmzZsbRGrz4uhwknXeS3XpaIRMYA7Ly0unOPOIVw8I2EEARGkH51r0Ikjysssuo0WLFtGWLVukx53lhUo3JFkwzxVekk0qF8sbmINAHGWoUREIKCEAolSCDZWiCBQhSW6rjH1L7lf1gmgdFpCUjHzAgAE9ctvCe9SBONoAAmoIgCjVcEOtnMutYcD4DOXUqVO7eZ1J0bM2gLbpXaYF5pSZjFzgb3PP2IZu0QcQ0IEAiFIHijVvI3qOMguOuGXWvG1k9aHyd5PepcuBOXH6sLlnrKIr1AECNhEAUdpEu4J9icAcjmCNPkeOHAkCeiZOnEhz5syh9vZ2Wrt2bVAs6sGIsnHBPzZh0+ldRs88cr5VvsqKvWlORs6PC4E5rnn4NvWNvoCADAIgShmUUKZ2CKh6l1U581jmUnjtjA0Ddh4BEKXzKoKAZSGQx7tMCsxpaWnx8swje5nTpk0Lzp2KVYCy9IB+gUDZCIAoy9YA+ncegXvuuScIPIrmSXU1MKcooHHnXIu2ifpAwGcEQJQ+aw+yW0Mg7F3yUY2nnnoquMqKH77nkS9BrkLGHEGSvFc8a9Ysa\/iiIyDgMgIgSpe1A9mcQoDJkvcu2cM8ceJEcDvKDTfc0AjM4UQAfAmyr2ceQZJOmRuEcQgBEKVDyoAo7iLA5MgkyQ8TIeda5YfJk39ngnQpFV5eJLHcmhcxlK8TAiDKOmkbY1VGgEmSSZFzrPpMiHEA2E4fqKwEVAQCJSEAoiwJeHQLBFxBgJML3HHHHbHibNq0KfYGGFdkhxxAwAYCIEobKKMPIAAEgAAQ8BYBEKW3qoPgQAAIAAEgYAMBEKUNlNEHEAACQAAIeIsAiNJb1UHwoghE89S6km+26LhQHwgAAb0IgCj14onWPEFAkCSfhVy+fHkgtQs3mHgCH8QEArVCAERZK3VjsAIBjvQcNWpUcLuJuLGEyTN6ywkQAwJAAAiAKGEDQOAjBECUMAUgAATiEABRwi6AwEcI4LJimAIQAAIgSo9sQGRL4QuRk6464quQZsyYQXv27ElNYK3jbkHu68477+y2VOkRnJmiCizXrFnT2LPMrIQC3RAQGCYFRYnEBln2OnLkSFq2bBnt27dPOdkB23xbWxutXr0a14TBTgsjAI+yMITmGhABJ8ePH+9BUIL8Ojs7M8mLg1T4KXobhK52zCGm1rKY4JGFRg2\/cK0kLPMkXI\/bP1aRjGWZOnVqcEXali1bVJpAHSAQIACidNwQkiYenkw+9alPZV6sq3OyqOIeHkhS\/wvAH1TsFYqVkDwfdTptTIdnqh8dtOgjAiBKD7QWnXhkb3oQE8Xp06cb3qSo+9xzz9Htt99Ozc3NAQK8HPbII48ES15DhgwJ\/i1uCa1KXiWWW80YvyBGbp29uQcffLAbcab1Gj2iI9ravXs3DR06tIdtPvzwwzRmzJigyTNnzvTwHnV+KJpBC636gACI0gMthb\/Ily5dSgsWLAikDh9tiBtG3FlB8W9cXnzxC8LgfxN7dKLPN954o9uSLZedNm1apifrOqxx2Lgus0\/yhW2K5ZZZ1o67xUT8G3\/QCdsMJ4oQ7YqPwuh7gZtRfLIad2UFUbqrm26ShSeec+fOSRFVHKnFeaNJpBh3AL8qBMNjE55I1AQQ0KPnpZAN3hG9xdlWnG0mkWJc1HLcqoqe0aGVOiEAovRI22Jyl\/k652HFTRyykxHXjyNKfKF7ZDAlihr2BIt82MXZWx6iTLLjEqFB1x4iAKL0SGmyATxiSEx0vK8TjvoDUXqkcI9FFfvqvBc+ZcoUiovcjg4vzr5BlB4bQYVEB1F6pMy8RAmP0iPlVkhUseQqVj6ivycNNW6rAERZIcPweCggSo+Ul5co0\/Yow8nA67hH6ZHavRI16bxkNHI7blBpqx3bt29vJB\/Is\/SKPUqvzMdZYUGUzqqmp2B5iTIt6lWVKKsS9eqR2r0RNXosJHzIP+1vYoBpUa+qRIk9dW\/Mx2lBQZROq6e7cHmJUgQy8H9FVp6ie5RVOkfpkeq9EPXHP\/5xcM4xKWo4K8UdDzKalafo0ivOUXphOs4LCaJ0XkXFBNTpAerMmlJsVKhdVQR0Hj9CZp6qWon9cYEo7WNuvUddXqCudqwDgA69QgC5Xr1SVy2EBVHWQM24PaQGSq7QEHV4grg9pACF5rMAAABXSURBVEIG4cBQQJQOKAEiAAEgAASAgLsIgCjd1Q0kAwJAAAgAAQcQAFE6oASIAASAABAAAu4iAKJ0VzeQDAgAASAABBxAAETpgBIgAhAAAkAACLiLwP8HCHmkAkcji74AAAAASUVORK5CYII=","height":221,"width":367}}
%---
